[dosbox]
machine=vgaonly

[cpu]
core=auto
cputype=386
cycles=7000

[mixer]
nosound=true

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
#imgmount c ~/Projects/craft386/craft386.img -t hdd -fs fat
echo LAlala
